### ISSUE TITLE
make : No such file or directory

### ISSUE THREAD

**Issue by AMChalkie** [a2iEditing/RNAEditingIndexer#11]
This is caused by : in the license section. Replacing ":" with "echo" just before the license text fixes it.

/mnts/bioinfo/git/RNAEditingIndexer/make/initResources.sh: line 12: :
This work is licensed under the Creative Commons Attribution-Non-Commercial-ShareAlike 4.0 International License.
To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/.
For use of the software by commercial entities, please inquire with Tel Aviv University at ramot@ramot.org.
© 2019 Tel Aviv University (Erez Y. Levanon, Erez.Levanon@biu.ac.il;
Eli Eisenberg, elieis@post.tau.ac.il;
Shalom Hillel Roth, shalomhillel.roth@live.biu.ac.il).
: No such file or directory

**Comment by sgennadi** [comment]
":" this is not a problem , error exist 
 Makefile:18: /make/Makefile: No such file or directory 
 
./configure.sh

This work is licensed under the Creative Commons Attribution-Non-Commercial-ShareAlike 4.0 International License.
To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/.
For use of the software by commercial entities, please inquire with Tel Aviv University at ramot@ramot.org.
(c) 2019 Tel Aviv University (Erez Y. Levanon, Erez.Levanon@biu.ac.il;
Eli Eisenberg, elieis@post.tau.ac.il;
Shalom Hillel Roth, shalomhillel.roth@live.biu.ac.il).

BEDTools Path Executable Test - Succeeded
BEDTools Version Test - Succeeded
SAMTools Path Executable Test - Succeeded
SAMTools Version Test - Succeeded
BAM Utils Path Executable Test - Succeeded
BAM Utils Run Test - Succeeded
BAM Utils Version Test - Succeeded
Java Path Executable Test - Succeeded
Java Run Test - Succeeded (java.version = 1.8.0)
Python 2.7 Path Executable Test - Succeeded
Python 2.7 Version Test - Succeeded

# make
Makefile:18: /make/Makefile: No such file or directory
make: *** No rule to make target `/make/Makefile'.  Stop.

**Comment by shalomhillelroth** [comment]
Thanks,
I fixed this typo.

Best,

Shalom Hillel Roth

**Comment by zhangm365** [comment]
> Thanks,
> I fixed this typo.
> 
> Best,
> 
> Shalom Hillel Roth

How to fix it?
