### ISSUE TITLE
Clarification on error messages

### ISSUE THREAD

**Issue by hengjwj** [a2iEditing/RNAEditingIndexer#37]
Hi, I wanted to check what the following error means:

> [2022-03-15 07:16:03,167] A2IEditingIndex ERROR    Failed Processing of L_stage22_rep1!
> Traceback (most recent call last):
>   File "Tools/EditingIndex/A2IEditingIndex.py", line 793, in load_and_process_sample
>   File "Tools/EditingIndex/A2IEditingIndex.py", line 922, in get_stranded_strands_and_counts
>   File "Tools/EditingIndex/A2IEditingIndex.py", line 964, in get_refseq_majority
> ZeroDivisionError: integer division or modulo by zero

I received a bunch of these for a particular region I'm investigating and in the output summary file, only three samples showed up even though the cmpileup was generated for all my samples. Is it safe to say the AEI and/or coverage is too low to detect in these samples?

Thank you!

**Comment by shalomhillelroth** [comment]
Hi,

That's definitely seems the case.
If you wish to double-check you can try to extract the coverage for those regions using samtools.
 
Best,

Shalom Hillel Roth
