### ISSUE TITLE
User flag doesn't seem to work

### ISSUE THREAD

**Issue by trenta** [a2iEditing/RNAEditingIndexer#7]
We have tried running this following the instructions on running as user: -u $(id -u ${USER}):$(id -g ${USER})

The output folder structure is still written as root.

I've tried using static uid and gid as a test and got the same results.

**Comment by shalomhillelroth** [comment]
Hi,

Can you specify more about your system configuration (OS, docker version etc.)?

I'm quite new to Docker myself, but I will try to look it up.

Best,

Shalom Hillel Roth

**Comment by trenta** [comment]
Hi,

Thanks for the reply.  We are running Ubuntu 18.04 with Docker version 19.03.1, build 74b1e89

No matter what user flag we use the output folder structure is owned by root.  I’ve tried with both -u and —user.  With static UID and GID entries to make sure it wasn’t the variables calling them.

Cheers

Trent

**Comment by trenta** [comment]
Closing issues as the problem was on my end.  The issue occurs when the directory structure doesn't already exist.  It gets created as the root user.  If the directory structure already exists this problem doesn't.
