### ISSUE TITLE
Docker permissions GenerateIndex

### ISSUE THREAD

**Issue by AMChalkie** [a2iEditing/RNAEditingIndexer#9]
Hi,

I'm seeing the following failure on index generation. I suggest Suggest adding the .fai to the docker resource download.

/Alistair

GenerateIndex - Starting!
Running: bedtools getfasta -name -bedOut -fi '/bin/AEI/RNAEditingIndexer/Resources/Genomes/MusMusculus/ucscMm10Genome.fa' -bed '/bin/AEI/RNAEditingIndexer/Resources/Regions/MusMusculus/ucscMM10SINE_B1_B2.bed.gz'
GenerateIndex - Indexing FASTA Records!
GenerateIndex - encountered unexpected line from bedtools, skipping line.
 Line:index file /bin/AEI/RNAEditingIndexer/Resources/Genomes/MusMusculus/ucscMm10Genome.fa.fai not found, generating...
GenerateIndex - encountered unexpected line from bedtools, skipping line.
 Line:could not open index file /bin/AEI/RNAEditingIndexer/Resources/Genomes/MusMusculus/ucscMm10Genome.fa.fai for writing!
GenerateIndex - getfasta Failed! Empty Output was Found

**Comment by AMChalkie** [comment]
Solution: 
Add this to Dockerfile: (once for each genome.fa)
RUN samtools faidx /bin/AEI/RNAEditingIndexer/Resources/Genomes/MusMusculus/ucscMm10Genome.fa

**Comment by shalomhillelroth** [comment]
Hi,
Thanks!

I'm working on a quick patch (to solve the configuration problems on different OS, using autoconf), hopefully in the next couple days I'll finish testing it.
I will add your suggestion, but to the initialization script (obviously with credit).

Best,

Shalom Hillel Roth
